set(_lic_root ${CMAKE_CURRENT_LIST_DIR}/../..)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  ${CMAKE_CURRENT_LIST_DIR}/licenses.manifest)
file(STRINGS ${CMAKE_CURRENT_LIST_DIR}/licenses.manifest _lic_names)
set(LICENSE_FILES "")
foreach(_lic IN LISTS _lic_names)
  if(NOT EXISTS "${_lic_root}/${_lic}")
    message(FATAL_ERROR "spec #9: лицензионный файл отсутствует: ${_lic_root}/${_lic}")
  endif()
  list(APPEND LICENSE_FILES ${_lic_root}/${_lic})
endforeach()
unset(_lic)
unset(_lic_root)
unset(_lic_names)
