# Граф ссылок для like-nesConfig.cmake выводится из целей дерева, а не переписывается руками:
# рукописная копия разошлась бы с деревом при первой новой зависимости, и это всплыло бы только
# у сборки игры против префикса. Неизвестный элемент — отказ конфигурирования, а не тихий пропуск.

function(like_nes_sdk_link_item item out)
  set(sdk ${LIKE_NES_SDK_STATIC} ${LIKE_NES_SDK_INTERFACE} webgpu)
  if(item MATCHES "^\\$<LINK_ONLY:(.+)>$")
    like_nes_sdk_link_item("${CMAKE_MATCH_1}" inner)
    if(inner STREQUAL "")
      set(${out} "" PARENT_SCOPE)
    else()
      set(${out} "$<LINK_ONLY:${inner}>" PARENT_SCOPE)
    endif()
    return()
  endif()
  if(item MATCHES "^\\$<")
    message(FATAL_ERROR "install_sdk: generator expression '${item}' in an SDK link interface "
                        "has no translation for like-nesConfig.cmake")
  endif()
  if(item IN_LIST sdk)
    set(${out} "like-nes::${item}" PARENT_SCOPE)
  elseif(item STREQUAL "Threads::Threads" OR item MATCHES "^-framework ")
    set(${out} "${item}" PARENT_SCOPE)
  elseif(TARGET ${item})
    # Объекты OBJECT-библиотеки уже лежат в архиве той цели, что её линкует.
    get_target_property(type ${item} TYPE)
    if(NOT type STREQUAL "OBJECT_LIBRARY")
      message(FATAL_ERROR "install_sdk: SDK target links '${item}' (${type}), which is not "
                          "part of the sdk component")
    endif()
    set(${out} "" PARENT_SCOPE)
  elseif(IS_ABSOLUTE "${item}")
    # Системная библиотека, найденная find_library: в префиксе остаётся её имя, путь у
    # машины игры свой. Файл из дерева или его сборки (FetchContent) системным не бывает: в
    # префиксе он стал бы `-l<имя>` и слинковался бы с чужой одноимённой библиотекой машины.
    foreach(root "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}")
      cmake_path(IS_PREFIX root "${item}" NORMALIZE inside)
      if(inside)
        message(FATAL_ERROR "install_sdk: link item '${item}' is built by this tree, not a "
                            "system library, and the SDK does not ship it")
      endif()
    endforeach()
    get_filename_component(name "${item}" NAME_WE)
    string(REGEX REPLACE "^lib" "" name "${name}")
    set(${out} "${name}" PARENT_SCOPE)
  elseif(item MATCHES "^[A-Za-z0-9_]+$")
    set(${out} "${item}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "install_sdk: link item '${item}' has no translation")
  endif()
endfunction()

# Значение уходит в Config bracket-аргументом: кавычка, `\` или `${` в макросе иначе переписали бы
# сгенерированный файл. Путь дерева в макросе унёс бы в префикс каталог машины сборки.
function(like_nes_sdk_defs tgt out)
  get_target_property(defs ${tgt} INTERFACE_COMPILE_DEFINITIONS)
  if(NOT defs)
    set(defs "")
  endif()
  if(defs MATCHES "\\$<|]==]")
    message(FATAL_ERROR "install_sdk: '${tgt}' exports definitions '${defs}' that "
                        "like-nesConfig.cmake cannot carry")
  endif()
  foreach(root "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}")
    string(FIND "${defs}" "${root}" at)
    if(at GREATER -1)
      message(FATAL_ERROR "install_sdk: '${tgt}' definitions '${defs}' carry a tree path")
    endif()
  endforeach()
  set(${out} "${defs}" PARENT_SCOPE)
endfunction()

# Опции и каталоги ссылок Config не переносит: непустые — отказ, а не тихая потеря в префиксе.
# Каталог include — только из LIKE_NES_SDK_INC_ALLOWED (install_sdk.cmake): чужой каталог дал бы
# игре в дереве то, чего в префиксе нет.
function(like_nes_sdk_check_props tgt)
  foreach(prop INTERFACE_COMPILE_OPTIONS INTERFACE_LINK_OPTIONS INTERFACE_LINK_DIRECTORIES)
    get_target_property(v ${tgt} ${prop})
    if(v)
      message(FATAL_ERROR "install_sdk: '${tgt}' exports ${prop} '${v}', which "
                          "like-nesConfig.cmake does not carry")
    endif()
  endforeach()
  get_target_property(dirs ${tgt} INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT dirs)
    return()
  endif()
  foreach(dir IN LISTS dirs)
    if(dir MATCHES "^\\$<INSTALL_INTERFACE:")
      continue()
    endif()
    if(dir MATCHES "^\\$<BUILD_INTERFACE:(.+)>$")
      set(dir "${CMAKE_MATCH_1}")
    endif()
    get_filename_component(dir "${dir}" ABSOLUTE)
    if(NOT dir IN_LIST LIKE_NES_SDK_INC_ALLOWED)
      message(FATAL_ERROR "install_sdk: '${tgt}' exports include directory '${dir}', which "
                          "the SDK neither ships nor allows")
    endif()
  endforeach()
endfunction()

function(like_nes_sdk_target_data tgt out)
  like_nes_sdk_check_props(${tgt})
  get_target_property(links ${tgt} INTERFACE_LINK_LIBRARIES)
  set(translated "")
  if(links)
    foreach(item IN LISTS links)
      like_nes_sdk_link_item("${item}" t)
      if(NOT t STREQUAL "")
        list(APPEND translated "${t}")
      endif()
    endforeach()
  endif()
  like_nes_sdk_defs(${tgt} defs)
  set(${out} "set(_ln_links_${tgt} [==[${translated}]==])\nset(_ln_defs_${tgt} [==[${defs}]==])\n"
      PARENT_SCOPE)
endfunction()

function(like_nes_sdk_static_name tgt out)
  set(${out} "${CMAKE_STATIC_LIBRARY_PREFIX}${tgt}${CMAKE_STATIC_LIBRARY_SUFFIX}" PARENT_SCOPE)
endfunction()

function(like_nes_sdk_config_data include_dirs out)
  set(data "set(_ln_static \"${LIKE_NES_SDK_STATIC}\")\n")
  string(APPEND data "set(_ln_interface \"${LIKE_NES_SDK_INTERFACE}\")\n")
  string(APPEND data "set(_ln_engine \"${LIKE_NES_SDK_ENGINE}\")\n")
  string(APPEND data "set(_ln_includes \"${include_dirs}\")\n")
  foreach(tgt IN LISTS LIKE_NES_SDK_STATIC)
    like_nes_sdk_static_name(${tgt} file)
    string(APPEND data "set(_ln_file_${tgt} \"${file}\")\n")
  endforeach()
  foreach(tgt IN LISTS LIKE_NES_SDK_STATIC LIKE_NES_SDK_INTERFACE)
    like_nes_sdk_target_data(${tgt} block)
    string(APPEND data "${block}")
  endforeach()
  like_nes_sdk_defs(webgpu defs)
  get_filename_component(runtime "${WGPU_RUNTIME_LIB}" NAME)
  string(APPEND data "set(_ln_defs_webgpu [==[${defs}]==])\nset(_ln_runtime \"${runtime}\")\n")
  set(${out} "${data}" PARENT_SCOPE)
endfunction()
