add_library(framework_scene STATIC scene_object.cpp scene_read.cpp scene_links.cpp)
target_include_directories(framework_scene PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(framework_scene PUBLIC framework_tilemap)

add_executable(framework_scene_test framework_scene_test.cpp)
target_link_libraries(framework_scene_test PRIVATE framework_scene)

add_executable(framework_scene_refusal_test framework_scene_refusal_test.cpp)
target_link_libraries(framework_scene_refusal_test PRIVATE framework_scene)
